### ISSUE TITLE
Cannot read property 'DEFAULT_PORT' of undefined。

### ISSUE THREAD

**Issue by wait-hua** [PaladinTyrion/nodejs_BYVoid_demo#1]
启动服务的时候, 在db.js中报错：
module.exports = new Db(settings.db, new Server(settings.host, Connection.DEFAULT_PORT, {}));
Cannot read property 'DEFAULT_PORT' of undefined。

**Comment by PaladinTyrion** [comment]
@wait-hua ：
Hello. I've checked this problem. 

"Connection" form lib of "mongodb" has been removed in the latest version 2.0.42. When I created this project, mongodb version is 0.9.x. So you can set DEFAULT_PORT by your own.

I‘ve  update project. And in fact I set this aggrument in "./setting.js". Usually the port of connection to mongodb is 27017.  It depends.

At last, do not foget booting up your Mongodb and read it's log. The log is the important road to lead everythings to be fine.

********************华丽的分割线*********************
目前mongoose的shema方案已经变成了普遍的ORM方案。如果您是学习BYVoid书里面的内容，还可以跟着我这个学一下。不过之前的库版本都太久了。建议你跟一下这些库的新版本文档。包括express版本也很高了。变化都非常大。
