### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by yaochiqkl** [PaladinTyrion/nodejs_BYVoid_demo#2]
![1](https://cloud.githubusercontent.com/assets/13565033/11034831/6b56e034-8729-11e5-97c5-38bf91df9735.png)

**Comment by PaladinTyrion** [comment]
Honey~
This means you are not running mongodb. Can you type 'mongod'(or 'sudo mongod') in Terminal for just starting your mongodb service?

**Comment by yaochiqkl** [comment]
Thanks a lot!!! I didn't realize that cause I know little about MongoDB.
I just installed it before and don't know to run it ( thought it is just like node or something, after installation it will be ran automatically )
I open mongo through cmd and it runs perfictly~ :laughing:
 Life seems to become hopefully again

**Comment by PaladinTyrion** [comment]
HAHA. Keep step forward~
